<?xml version="1.0"?>
<package format="3">
  <name>equirec2perspec</name>
  <version>0.1.0</version>
  <description>
    A ROS package for equirectangular to perspective image conversion
  </description>
  <maintainer email="xmj@sjtu.edu.cn">Minjie Xu</maintainer>
  <author email="xmj@sjtu.edu.cn">Minjie Xu</author>
  <license>BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>libopencv-dev</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>image_transport</build_depend>

  <exec_depend>libopencv-dev</exec_depend>
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_transport</exec_depend>

  <build_export_depend>libopencv-dev</build_export_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
